name: CLI Regression Test

on: [push, pull_request]

jobs:
  cli-regression-test:

    runs-on: ubuntu-latest

    permissions:
      actions: read

    defaults:
      run:
        shell: bash -ileo pipefail {0}

    steps:
      - name: Checkout Streamlit code
        uses: actions/checkout@v3
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.7"
      - uses: ./.github/actions/update_submodules
      - uses: ./.github/actions/pre_cache
      - uses: ./.github/actions/pre_make
      - uses: ./.github/actions/make_init
      - name: Build Package - Fast
        timeout-minutes: 120
        run: |
          source venv/bin/activate
          sudo apt-get install rsync
          BUILD_AS_FAST_AS_POSSIBLE=1 make package
      - name: Run CLI regression tests
        run: |
          source venv/bin/activate
          export SKIP_VERSION_CHECK=true
          make cli-regression-tests